affgen/urls.py
from django.conf.urls import include, url
from django.views.decorators.cache import cache_page

from .import views

urlpatterns = [
    url(r'^$',views.homeaffgen, name='homeaffgen'),
    url(r'^elus/', views.elus, name='elus'),
    url(r'^comptes-rendus/$', views.comptesrendus, name='comptesrendus'),
    url(r'^comptes-rendus/(?P<idcpt>[^\/]+).html$', views.compterendu, name='compterendu')
]

epn/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^form-fiche-inscription.html$', views.formficheinscription, name="formficheinscription"),
    url(r'^inscription/(?P<uuid>[^\/]+)$', views.inscription, name='inscription'),
    url(r'^getpdf/(?P<uuid>[^\/]+)$', views.getpdf, name='getpdf'),
    url(r'^exportepn/$', views.exportepn, name='exportepn'),


]

lettreinformations/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^get-token.html$', views.mailJetGetToken, name="mailjet-get-token"),
    url(r'^mailjet-ajax.html$', views.mailJetAjax, name="mailjet-ajax"),
    url(r'^mailjet-post.html$', views.mailJetPost, name="mailjet-post"),
    url(r'^mailjet-reponse-(?P<reponse>[^\/]+).html$', views.mailJetReponse, name="mailjet-reponse"),
    url(r'^validation/(?P<hash>[^\/]+).html$', views.mailValidation, name="mail-validation"),
    url(r'^$', views.mailForm, name="mail-form"),
]

valdyerresweb/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.views.generic import TemplateView

from filebrowser.sites import site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'essai.views.home', name='home'),
    # url(r'^essai/', include('essai.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^agenda/', include('evenements.urls')),
    url(r'^equipements/', include('equipements.urls')),
    url(r'^tourisme/', include('sitestouristiques.urls')),
    url(r'^cinemas/', include('cinemas.urls')),
    url(r'^services/', include('services.urls')),
    url(r'^annoncesemploi/', include('annoncesemploi.urls')),
    url(r'^mail/', include('lettreinformations.urls')),
    url(r'^forms/', include('forms.urls')),
    url(r'^deveco/', include('deveco.urls')),
    url(r'^epn/', include('epn.urls')),
    url(r'^agglo/', include('affgen.urls')),
    url(r'', include('editorial.urls')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^search/', include('haystack.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

affgen/models.py
# -*- coding: utf-8 -*-

from django.db import models
from localisations.models import Ville
from filebrowser.fields import FileBrowseField


SEXE = (
    ('ind', u'Indeterminé'),
    ('homme', u'Homme'),
    ('femme', u'Femme')
)


# Create your models here.
class Elu(models.Model):
    nom = models.CharField(max_length=255)
    prenom = models.CharField(max_length=255)
    sexe = models.CharField(max_length=5, choices=SEXE, default='ind')
    photo = models.ImageField(upload_to="affgen", verbose_name="Photo", blank=True, null=True)
    ville = models.ForeignKey(Ville)
    publie = models.BooleanField(default=False,verbose_name=u"Publié")

    class Meta:
        ordering = ['nom']

    def __str__(self):
        return self.nom


class TitreHorsAgglo(models.Model):
    elu = models.ForeignKey(Elu)
    nom = models.CharField(max_length=255)
    index = models.PositiveSmallIntegerField(verbose_name="ordre d'apparition")

    class Meta:
        ordering = ['index']


class QualifMandat(models.Model):
    nom = models.CharField(max_length=255)
    feminin = models.CharField(max_length=255)
    index = models.PositiveSmallIntegerField(verbose_name="ordre d'apparition")

    class Meta:
        ordering = ['index']

    def __str__(self):
        return self.nom


class MandatAgglo(models.Model):
    elu = models.ForeignKey(Elu)
    nom = models.CharField(max_length=255)
    qualif = models.ForeignKey(QualifMandat)
    index = models.PositiveSmallIntegerField(verbose_name="ordre d'apparition")

    class Meta:
        ordering = ['index']
        verbose_name = u"Mandat dans l'agglo"
        verbose_name_plural = u"Mandats dans l'agglo"


ENTITE = (
    ('vyvs', u'Val d’Yerres Val de Seine'),
    ('casvs', u'Val de Seine'),
    ('cavy', u'Val d’Yerres')
)


class Cptrendu(models.Model):
    date = models.DateField(verbose_name="Date du conseil")
    entite = models.CharField(max_length=5, choices=ENTITE, default='vyvs')
    document = models.FileField("Document PDF", max_length=200,  upload_to="uploads/comptesrendus")

    class Meta:
        ordering = ['-date']
        verbose_name = u"Compte rendu conseil"
        verbose_name_plural = u"Comptes rendus"

    def deliberations(self):
        return Deliberation.objects.all().filter(compterendu=self.id)

class Deliberation(models.Model):
    compterendu = models.ForeignKey(Cptrendu)
    numreference = models.CharField(verbose_name="Numéro de référence", max_length=32)
    titre = models.CharField(max_length=255)
    document = models.FileField("Fichier PDF", upload_to="uploads/deliberations/")

    class Meta:
        ordering = ['numreference']
        verbose_name = u"Délibération"
        verbose_name_plural = u"Délibérations"

affgen/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from .models import QualifMandat,Elu, Cptrendu
from collections import namedtuple

from django.shortcuts import render_to_response, redirect, get_object_or_404, \
    get_list_or_404


def homeaffgen(request):
    return redirect('home')


def elus(request):
    mandats = QualifMandat.objects.all().order_by('index')
    elusst = list()
    elusnd = list()

    MandatTuple = namedtuple('MandatTuple','mandat listeelus')

    for mandat in mandats[:3]:

        elustmp = list()
        leselus =Elu.objects.filter(publie=True, mandatagglo__qualif_id=mandat.id).order_by('mandatagglo__index').select_related()
        for elu in leselus:
            elustmp.append(elu)

        mandatagglo = MandatTuple(mandat, elustmp)
        elusst.append(mandatagglo)


    for mandat in mandats[3:]:
        leselus = Elu.objects.filter(publie=True, mandatagglo__qualif_id=mandat.id).order_by(
            'ville','mandatagglo__index').select_related()
        for elu in leselus:
            elusnd.append(elu)


    return render_to_response('liste_elus.html', {'elusst': elusst, 'elusnd':elusnd})


def comptesrendus(request):
    cptrd = Cptrendu.objects.all().order_by('-date')
    return render_to_response('comptes_rendus.html', {'cptrd': cptrd})

def compterendu(request, idcpt):
    cptrendu = get_object_or_404(Cptrendu, date=idcpt)
    return render_to_response('compte_rendu.html', {'cptrendu': cptrendu})

affgen/templates/compte_rendu.html
{% extends "include/main.html" %}
{% load filtres %}
{% load aidefilters %}
{% load eventfilters %}
{% load menufilters %}
{% load aidefilters %}
{% load tz %}

{% block title %}Conseil Communautaire du {{ cptrendu.date }}{% endblock %}

{% block meta-description %}Conseil Communautaire du {{ cptrendu.date }} compte rendu {% if cptrendu.deliberations %} et
    délibérations {% endif %} au format PDF{% endblock %}

{% block menu %}{% getmenu %}{% endblock %}

{% block contenu %}



    <div class="container">
        <div class="row-fluid">
            <div class="col-md-12">
                <ul class="breadcrumb">
                    <li><a href="/">Accueil</a></li>
                    <li><a href="{% url 'comptesrendus' %}">Comptes rendus du Conseil Communautaire</a></li>
                    <li class="active">Conseil Communautaire du {{ cptrendu.date }}</li>
                </ul>
            </div>
            <div class="col-md-12">
                <h1><a href="{% url 'compterendu' cptrendu.date %}">Conseil Communautaire du {{ cptrendu.date }} </a>
                </h1>
                <h2>Compte rendu sommaire</h2>
                <p>
                    Le compte rendu de la scéance du {{ cptrendu.date }} est disponible au format PDF : <a
                        href="{{ cptrendu.document.url }}" class="btn btn-info"><i class="fa fa-share"></i> Voir le
                    compte rendu</a></td>
                </p>

                {% if cptrendu.deliberations %}
                    <h2>Les délibérations</h2>
                    <table class="table  table-hover">
                        <tbody>
                        <thead>
                        <tr>
                            <th>Référence</th>
                            <th>Objet</th>
                            <th>Consulter</th>
                        </tr>
                        </thead>

                        {% for item in cptrendu.deliberations %}
                           <tr>
                                <td>{{ item.numreference }}</td>
                                <td>{{ item.titre }}</td>
                                <td><a href="{{ item.document.url }}" class="btn btn-info"><i class="fa fa-share"></i>
                                    Voir la délibération {{ item.numreference }}</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block jsload %}
    {% include "include/jquery-bootstrap.html" %}
{% endblock %}

affgen/templates/comptes_rendus.html
{% extends "include/main.html" %}
{% load filtres %}
{% load aidefilters %}
{% load eventfilters %}
{% load menufilters %}
{% load aidefilters %}
{% load tz %}

{% block title %}Comptes rendus du Conseil Communautaire du Val d'Yerres Val de Seine{% endblock %}

{% block meta-description %}Les comptes rendus du Conseil Communautaire de la communauté d'agglomération Val d'Yerres Val de Seine{% endblock %}

{% block menu %}{% getmenu %}{% endblock %}

{% block contenu %}
    <div class="container">
    <div class="row-fluid">
        <div class="col-md-12">
            <ul class="breadcrumb">
                <li><a href="/">Accueil</a></li>
                <li class="active">Comptes rendus du Conseil Communautaire
                <li>
            </ul>
        </div>
        <div class="col-md-12">
            <h1><a href="{% url 'comptesrendus' %}">Comptes rendus du Conseil Communautaire</a></h1>
        <ul>

        {% regroup cptrd by date|date:"Y" as objects_by_year %}
            {% for year in objects_by_year %}
                <li>{{ year.grouper }}</li>
                <table class="table  table-hover">
                <tbody>
                {% for item in year.list %}
				<tr>
					<td>Compte rendu du {{item.date}}</td>
    				<td><a href="{% url 'compterendu' item.date %}" class="btn btn-info"><i class="fa fa-share"></i> Voir le compte rendu</a></td>
				</tr>
                {% endfor %}
                </tbody>
                </table>
            {% endfor %}

        </div>
    </div>
    </div>
{% endblock %}

{% block jsload %}
    {% include "include/jquery-bootstrap.html" %}
{% endblock %}

affgen/templates/liste_elus.html
{% extends "include/main.html" %}
{% load filtres %}
{% load aidefilters %}
{% load eventfilters %}
{% load menufilters %}
{% load aidefilters %}
{% load tz %}

{% block title %}Les élus du Val d'Yerres Val de Seine{% endblock %}

{% block meta-description %}Les élus de la communauté d'agglomération Val d'Yerres Val de Seine dans l'Essonne{% endblock %}

{% block menu %}{% getmenu %}{% endblock %}

{% block contenu %}



    <div class="container">
        <div class="row-fluid">
            <div class="col-md-12">
                <ul class="breadcrumb">
                    <li><a href="/">Accueil</a></li>
                    <li class="active">Vos élus
                    <li>
                </ul>
            </div>
            <div class="col-md-12">
                <h1>Vos élus </h1>
                {% for fonction in elusst %}
                    {% if fonction.listeelus|length > 0 %}
                    <h3>Le{{fonction.listeelus|length|pluralize }}
                        {% with fonction.mandat.nom|splitwords as parts %}
                            {% for word in parts %}
                                {{ word }}{{ fonction.listeelus|length|pluralize }}
                            {% endfor %}
                            </h3>
                        {% endwith %}
                    <table class="table  table-striped">
                        {% for elu in fonction.listeelus %}
                            <tr>
                                <td><img alt="photo de {{ elu.nom }} {{ elu.prenom }}" class="img-responsive"
                                         src="{{ elu.photo |resize:'100x100x1' }}"></td>
                                <td>{{ elu.prenom }} {{ elu.nom }}</td>
                                <td>
                                    <p>
                                        {% for titre in elu.mandatagglo_set.all %}
                                            {{ titre.nom }}<br>

                                        {% endfor %}
                                        {% for titre in elu.titrehorsagglo_set.all %}
                                            {{ titre.nom }}<br>

                                        {% endfor %}
                                    </p>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                    {% endif %}
                {% endfor %}

                {% regroup elusnd by ville.nom as villes_list %}

                <h2>Les conseillers communautaires</h2>
                {% for ville in villes_list %}
                    <h3>{{ ville.grouper }}</h3>
                    <table class="table  table-striped">
                        {% for elu in ville.list %}
                            <tr>
                                <td><img alt="photo de {{ elu.nom }} {{ elu.prenom }}" class="img-responsive"
                                         src="{{ elu.photo |resize:'100x100x1' }}"></td>
                                <td>{{ elu.prenom }} {{ elu.nom }}</td>
                                <td>
                                    <p>
                                        {% for titre in elu.mandatagglo_set.all %}
                                            {{ titre.nom }}<br>

                                        {% endfor %}
                                        {% for titre in elu.titrehorsagglo_set.all %}
                                            {{ titre.nom }}<br>

                                        {% endfor %}
                                    </p>
                                </td>


                            </tr>
                        {% endfor %}
                    </table>
                {% endfor %}
                </table>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block jsload %}
    {% include "include/jquery-bootstrap.html" %}
{% endblock %}